image: ros:kinetic-ros-core

variables:
  ROS_PACKAGES_TO_INSTALL: "uuid-msgs"

before_script:
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null
  - pwd
  - ls src/
  - ls src/libs
  - ../.preprocess.sh

catkin_make:
  stage: build
  script:
    - catkin_make

