image: ros:indigo-ros-core

variables:
  ROS_PACKAGES_TO_INSTALL: ""

before_script:
  - PWD_DIR=$(pwd)
  - pwd
  - ls 
  - cd ./motoman_project
  - ./.preprocess.sh
  - cd ..
  - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
  - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

catkin_make:
  stage: build
  script:
    - catkin_make

catkin_make tests:
  stage: test
  script:
    - catkin_make run_tests
